version: "3.8"
networks:
  time-breaker:
    driver: "bridge"
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: on-failure
    command: sh -c 'php-fpm'
    networks:
      - time-breaker
    container_name: time-breaker_php-fpm
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    networks:
      - time-breaker
    container_name: time-breaker_postgres
