version: "3.8"
volumes:
  postgres:
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "6001:6001"
      - "443:443"
    volumes:
      - ".:/time-breaker:consistent"
    working_dir: "/time-breaker"
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=time_breaker
      - POSTGRES_USER=chronos
      - POSTGRES_PASSWORD=secret
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ".:/time-breaker:consistent"
      - "./docker/nginx:/etc/nginx"
    depends_on:
      - php-fpm
    restart: on-failure
    networks:
      - time-breaker
    container_name: time-breaker_nginx
